### ISSUE TITLE
如何部署

### ISSUE THREAD

**Issue by ponycloud235** [zihjiang/filling#59]
部署步骤
第一步：执行 mvn jar:jar install:install，打包jar
1.flink-service，下的application-dev.yaml
   修改application.flink.jar指向flling-core的jar包，debug-lib-dir 
2. 搭建flink，修改application-dev.yaml flink.url 指向安装的flink 8081端口

疑问，flink是否有版本要求？ 除了以上是否还有需要调整的地方

**Comment by zihjiang** [comment]
参考
https://zihjiang.github.io/filling-book/%E9%83%A8%E7%BD%B2/quick-install.html
 使用docker快速部署

**Comment by ponycloud235** [comment]
嗯  已经使用源码部署成功了，感谢答复
